"""empty message

Revision ID: 47506c084587
Revises: 
Create Date: 2021-03-16 19:22:08.947405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47506c084587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('no_room', sa.String(length=10), nullable=True),
    sa.Column('no_bath', sa.String(length=10), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
